### ISSUE TITLE
pyProbabilityDistributionFit-0.0.4-py3-none-any.whl only returns the dist-info folder

### ISSUE THREAD

**Issue by dmkeijzer** [WolfgangFahl/pyProbabilityDistributionFit#6]
Relatively new to Python (coding in general) but have not come across this issue before and there does not seem to be an easy fix but it might be on me. Anyways, when I try pip installing using "pip install pyProbabilityDistributionFit", it says it has been successfully installed, however when I try importing it, it is not recognized. So, when I looked through my environment I only found the dist-info folder. I tried it multiple times but gives the same result each time. I used the wheel mentioned in the title.

Any help would be greatly appreciated!

**Comment by WolfgangFahl** [comment]
the package content should be in the "pdffit" folder shown by
```bash
pip show pyProbabilityDistributionFit
```
for good measure i created a new version 0.0.5 release a minute ago
